In [1]:
import pandas as pd

### Reading in CSVs
Creating Dataframes and a dictionary for use in the transformation

In [2]:
url_GDP_Income = '../Raw Files/US GDP and Personal Income.csv'
url_US_Total_Employment = '../Raw Files/US Total employment By States.csv'

In [6]:
US_GDP_Income = pd.read_csv(url_GDP_Income, skiprows=3, skipfooter=6, engine='python')
US_Total_Employment = pd.read_csv(url_US_Total_Employment, index_col=1, skipfooter=4, engine='python')

### Cleaning Up and Melting

US GDP and Personal Income

In [ ]:
US_GDP_Income = US_GDP_Income.iloc[0:156]
US_GDP_Income['GeoName'] = US_GDP_Income['GeoName'].replace('Alaska *', 'Alaska')
US_GDP_Income.rename(columns={'variable':'Year_Quarter','GeoName':'State'}, inplace=True)
US_GDP_Income = US_GDP_Income.melt(id_vars=['GeoFIPS', 'State', 'LineCode', 'Description'])
US_GDP_Income

,GeoFIPS,GeoName,LineCode,Description,2015:Q1,2015:Q2,2015:Q3,2015:Q4,2016:Q1,2016:Q2,...,2023:Q3,2023:Q4,2024:Q1,2024:Q2,2024:Q3,2024:Q4,2025:Q1,2025:Q2,2025:Q3,2025:Q4
0,0,United States,1,"Personal income (millions of dollars, seasonal...",15276302.2,15423817.5,15541187.0,15627145.2,15703395.6,15784190.6,...,23724337.7,24020535.7,24466466.2,24790949.1,25014714.4,25318322.2,25713267.6,25982179.3,26263006.0,26480869.9
1,0,United States,2,"Population (midperiod, persons) 1",320914934.0,321493605.0,322178548.0,322864872.0,323436591.0,324025804.0,...,337198150.0,338045415.0,338791198.0,339585988.0,340269222.0,340764135.0,341139178.0,341545528.0,341935671.0,342192136.0
2,0,United States,3,Per capita personal income (dollars) 2,47602.0,47976.0,48238.0,48402.0,48552.0,48713.0,...,70357.0,71057.0,72217.0,73003.0,73514.0,74299.0,75375.0,76072.0,76807.0,77386.0
3,1000,Alabama,1,"Personal income (millions of dollars, seasonal...",185291.7,187010.9,188719.5,188876.9,189491.0,190311.1,...,280991.1,285011.4,289618.5,294230.3,297585.6,300927.5,306492.5,309858.4,310778.7,312496.1
4,1000,Alabama,2,"Population (midperiod, persons) 1",4902063.0,4906482.0,4912678.0,4919092.0,4923738.0,4928639.0,...,5124036.0,5135793.0,5146054.0,5157199.0,5167419.0,5175620.0,5182030.0,5189053.0,5196713.0,5203147.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,55000,Wisconsin,2,"Population (midperiod, persons) 1",5789333.0,5792344.0,5797588.0,5802969.0,5806252.0,5810167.0,...,5934346.0,5941589.0,5946883.0,5953450.0,5959849.0,5964532.0,5966961.0,5970342.0,5974683.0,5977495.0
152,55000,Wisconsin,3,Per capita personal income (dollars) 2,45518.0,45831.0,46074.0,46257.0,46307.0,46378.0,...,65166.0,65987.0,66889.0,67565.0,68108.0,68675.0,69615.0,70350.0,70994.0,71338.0
153,56000,Wyoming,1,"Personal income (millions of dollars, seasonal...",33121.6,32827.5,32768.2,32304.9,31364.9,30970.0,...,48780.6,49515.7,50000.2,50669.6,51098.4,51493.4,52224.3,52938.8,52962.5,53368.3
154,56000,Wyoming,2,"Population (midperiod, persons) 1",582725.0,583318.0,583542.0,583195.0,582662.0,582184.0,...,584985.0,585550.0,585924.0,586438.0,587041.0,587639.0,588005.0,588450.0,589015.0,589456.0
155,56000,Wyoming,3,Per capita personal income (dollars) 2,56839.0,56277.0,56154.0,55393.0,53830.0,53196.0,...,83388.0,84563.0,85336.0,86402.0,87044.0,87628.0,88816.0,89963.0,89917.0,90538.0

US Total employment By States

In [28]:
US_Total_Employment.drop(columns = ['2025'], inplace=True)
US_Total_Employment = US_Total_Employment.melt(ignore_index=False)
US_Total_Employment.reset_index(inplace=True)
US_Total_Employment.rename(columns = {'GeoName':'State','variable':'Year','value':'People'}, inplace=True)

In [9]:
US_GDP_Income

,GeoFIPS,GeoName,LineCode,Description,Year_Quarter,value
0,0,United States,1,"Personal income (millions of dollars, seasonal...",2015:Q1,15276302.2
1,0,United States,2,"Population (midperiod, persons) 1",2015:Q1,320914934.0
2,0,United States,3,Per capita personal income (dollars) 2,2015:Q1,47602.0
3,1000,Alabama,1,"Personal income (millions of dollars, seasonal...",2015:Q1,185291.7
4,1000,Alabama,2,"Population (midperiod, persons) 1",2015:Q1,4902063.0
...,...,...,...,...,...,...
6859,55000,Wisconsin,2,"Population (midperiod, persons) 1",2025:Q4,5977495.0
6860,55000,Wisconsin,3,Per capita personal income (dollars) 2,2025:Q4,71338.0
6861,56000,Wyoming,1,"Personal income (millions of dollars, seasonal...",2025:Q4,53368.3
6862,56000,Wyoming,2,"Population (midperiod, persons) 1",2025:Q4,589456.0
6863,56000,Wyoming,3,Per capita personal income (dollars) 2,2025:Q4,90538.0

In [5]:
US_GDP_Income

,GeoFIPS,GeoName,LineCode,Description,Year_Quarter,value
0,0,United States,1,"Personal income (millions of dollars, seasonal...",2015:Q1,15276302.2
1,0,United States,2,"Population (midperiod, persons) 1",2015:Q1,320914934.0
2,0,United States,3,Per capita personal income (dollars) 2,2015:Q1,47602.0
3,1000,Alabama,1,"Personal income (millions of dollars, seasonal...",2015:Q1,185291.7
4,1000,Alabama,2,"Population (midperiod, persons) 1",2015:Q1,4902063.0
...,...,...,...,...,...,...
6859,55000,Wisconsin,2,"Population (midperiod, persons) 1",2025:Q4,5977495.0
6860,55000,Wisconsin,3,Per capita personal income (dollars) 2,2025:Q4,71338.0
6861,56000,Wyoming,1,"Personal income (millions of dollars, seasonal...",2025:Q4,53368.3
6862,56000,Wyoming,2,"Population (midperiod, persons) 1",2025:Q4,589456.0
6863,56000,Wyoming,3,Per capita personal income (dollars) 2,2025:Q4,90538.0

In [ ]:
US_GDP_Income = US_GDP_Income['GeoName'].replace('Alaska *','Alaska')
US_GDP_Income