In [1]:
import pandas as pd

### Reading in CSVs
Creating Dataframes and a dictionary for use in the transformation

In [2]:
url_labor_force = '../data/raw/Labor_Force_Participation_by_State/monthly.csv'
url_construction = '../data/raw/Construction/monthly.csv'
url_education = '../data/raw/Education/monthly.csv'
url_hospitality = '../data/raw/Hospitality/monthly.csv'
url_manufacturing = '../data/raw/Manufacturing/monthly.csv'

In [3]:
df_labor_force = pd.read_csv(url_labor_force, index_col=0)
df_construction = pd.read_csv(url_construction, index_col=0)
df_education = pd.read_csv(url_education, index_col=0)
df_hospitality = pd.read_csv(url_hospitality, index_col=0)
df_manufacturing = pd.read_csv(url_manufacturing, index_col=0)

In [4]:
dfs = {'us_labor_force':df_labor_force,
'us_construction':df_construction,
'us_education':df_education, 
'us_hospitality':df_hospitality, 
'us_manufacturing':df_manufacturing,}

In [5]:
#Checking Import
df_manufacturing

,AKMFG,ARMFG,AZMFG,CAMFG,COMFG,CTMFG,DEMFG,FLMFG,GAMFG,HIMFG,...,SMU11000003000000001SA,TNMFG,TXMFG,UTMFG,VAMFG,VTMFG,WAMFG,WIMFG,WVMFG,WYMFG
observation_date,,,,,,,,,,,,,,,,,,,,,
1990-01-01,12.4,218.4,177.3,1985.5,169.7,305.1,42.6,521.3,524.9,21.0,...,7.5,502.7,938.8,101.6,391.3,44.2,337.7,524.5,81.9,8.9
1990-02-01,12.4,218.9,177.6,1985.4,170.0,304.8,46.7,519.9,526.9,21.0,...,7.5,503.8,939.4,101.9,391.0,43.7,337.4,527.9,82.1,8.8
1990-03-01,12.9,217.8,177.1,1982.7,170.3,304.5,46.9,517.8,528.2,21.0,...,7.5,504.0,940.8,101.9,391.6,43.4,338.6,526.8,82.5,9.1
1990-04-01,13.7,219.0,176.5,1983.1,171.1,304.8,46.7,513.4,529.4,20.6,...,7.4,503.9,942.2,104.1,390.6,43.0,337.2,525.1,82.7,9.0
1990-05-01,14.5,219.2,176.7,1980.3,170.4,302.9,46.7,513.2,527.5,20.4,...,7.3,504.7,940.7,104.1,389.1,43.2,336.4,525.3,82.7,9.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-01,12.9,158.7,192.6,1214.4,146.3,151.5,26.4,425.8,425.6,13.0,...,1.0,353.3,981.0,154.3,233.3,27.3,269.6,455.7,45.0,10.4
2025-11-01,12.3,158.8,192.7,1212.2,145.5,151.8,26.2,424.2,424.3,13.0,...,1.0,352.8,980.1,153.6,232.8,27.3,267.9,454.8,44.9,10.4
2025-12-01,12.7,158.5,191.9,1213.1,145.4,151.2,26.5,424.9,427.0,13.0,...,1.0,352.0,981.1,154.3,232.3,27.4,269.7,454.6,45.0,10.4
2026-01-01,12.5,159.0,192.8,1214.3,144.3,152.2,26.3,428.7,425.7,13.1,...,1.0,351.9,977.0,154.4,230.2,27.5,271.0,451.6,44.9,10.4
2026-02-01,12.6,158.7,193.1,1211.9,143.7,152.6,26.4,428.5,425.5,13.1,...,1.0,351.9,979.5,153.6,228.6,27.4,271.1,451.5,44.9,10.3

### Creating Mapping between State Abbrivations and Names
Every CSV uses the same 2 letter abbrivation to identify the State

In [6]:
mapping = {'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'DS': 'Unknown / Not a U.S. state',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WY': 'Wyoming'}

### Indivual Cleaning for Manufacturing
The columns for Manufacturing in District of Columbia and Manufacturing in Alabama are given non-standard ID codes

In [7]:
manufacturing_mapping = {'SMS11000003000000001' : 'DC', 
                         'SMU01000003000000001SA' : 'AL'}
for name, df in dfs.items():
    if name == 'us_manufacturing':
        df.rename(columns=manufacturing_mapping, inplace=True)
        df.drop(columns='SMU11000003000000001SA', inplace=True)
    else:
        pass

### Bulk Transformations
Changing each csv's different column code of (State + Survey) into the State Name

In [8]:
for name, df in dfs.items():
    df.rename(columns=lambda x: x[:2], inplace=True)
    df.rename(columns=mapping, inplace=True)
    df.rename_axis(None,inplace=True)

### Individual Cleaning
Labor Force has one null State and no information for October 2025

Construction has no information for Tennessee

In [9]:
# df_labor_force cleaning
df_labor_force.drop('Unknown / Not a U.S. state', axis=1, inplace=True)
df_labor_force.drop('2025-10-01', axis=0, inplace=True)
#df_construction cleaning
df_construction.drop('Tennessee', axis=1, inplace=True)

### Transposing and Melting
Making it so that rows are states and columns are dates to align with Statistics Canada

In [10]:
dfs = {name: df.T for name, df in dfs.items()}
dfs = {name: df.melt(ignore_index=False) for name, df in dfs.items()}
dfs = {name: df.reset_index(names='State') for name, df in dfs.items()}
dfs = {name: df.rename(columns={'variable':"Date"}) for name, df in dfs.items()}

In [11]:
#Final Checking
for name, df in dfs.items():
    print(name)
    display(df)

us_labor_force

              State        Date       value
0            Alaska  2015-01-01    362704.0
1           Alabama  2015-01-01   2166864.0
2          Arkansas  2015-01-01   1331412.0
3           Arizona  2015-01-01   3090768.0
4        California  2015-01-01  18818212.0
...             ...         ...         ...
6778        Vermont  2026-02-01    344047.0
6779     Washington  2026-02-01   4066446.0
6780      Wisconsin  2026-02-01   3126595.0
6781  West Virginia  2026-02-01    782052.0
6782        Wyoming  2026-02-01    288501.0

[6783 rows x 3 columns]

us_construction

              State        Date  value
0            Alaska  2015-01-01   18.2
1           Alabama  2015-01-01   80.7
2          Arkansas  2015-01-01   47.7
3           Arizona  2015-01-01  124.2
4        California  2015-01-01  706.5
...             ...         ...    ...
6427        Vermont  2026-02-01   16.4
6428     Washington  2026-02-01  217.2
6429      Wisconsin  2026-02-01  153.7
6430  West Virginia  2026-02-01   36.7
6431        Wyoming  2026-02-01   23.9

[6432 rows x 3 columns]

us_education

              State        Date   value
0            Alaska  2015-01-01    47.8
1           Alabama  2015-01-01   231.3
2          Arkansas  2015-01-01   173.2
3           Arizona  2015-01-01   392.5
4        California  2015-01-01  2420.6
...             ...         ...     ...
6293       Virginia  2026-02-01   628.8
6294        Vermont  2026-02-01    65.9
6295     Washington  2026-02-01   570.1
6296      Wisconsin  2026-02-01   501.1
6297  West Virginia  2026-02-01   147.2

[6298 rows x 3 columns]

us_hospitality

              State        Date   value
0            Alaska  2015-01-01    34.9
1           Alabama  2015-01-01   186.9
2          Arkansas  2015-01-01   109.4
3           Arizona  2015-01-01   295.9
4        California  2015-01-01  1792.2
...             ...         ...     ...
6829        Vermont  2026-02-01    36.3
6830     Washington  2026-02-01   344.4
6831      Wisconsin  2026-02-01   289.8
6832  West Virginia  2026-02-01    70.7
6833        Wyoming  2026-02-01    38.5

[6834 rows x 3 columns]

us_manufacturing

               State        Date   value
0             Alaska  1990-01-01    12.4
1           Arkansas  1990-01-01   218.4
2            Arizona  1990-01-01   177.3
3         California  1990-01-01  1985.5
4           Colorado  1990-01-01   169.7
...              ...         ...     ...
22129        Vermont  2026-02-01    27.4
22130     Washington  2026-02-01   271.1
22131      Wisconsin  2026-02-01   451.5
22132  West Virginia  2026-02-01    44.9
22133        Wyoming  2026-02-01    10.3

[22134 rows x 3 columns]

### Saving to CSV

In [12]:
for name, df in dfs.items():
    df.to_csv(f'../data/clean/{name}.csv')