In [41]:
import pandas as pd

### Reading in CSVs
Creating Dataframes and a dictionary for use in the transformation

In [42]:
url_labor_force = '../data/raw/Labor_Force_Participation_by_State/monthly.csv'
url_construction = '../data/raw/Construction/monthly.csv'
url_education = '../data/raw/Education/monthly.csv'
url_hospitality = '../data/raw/Hospitality/monthly.csv'
url_manufacturing = '../data/raw/Manufacturing/monthly.csv'

In [43]:
df_labor_force = pd.read_csv(url_labor_force, index_col=0)
df_construction = pd.read_csv(url_construction, index_col=0)
df_education = pd.read_csv(url_education, index_col=0)
df_hospitality = pd.read_csv(url_hospitality, index_col=0)
df_manufacturing = pd.read_csv(url_manufacturing, index_col=0)

### Normalizing Data and Intial Cleaning
Making it so that all the data is x1000 people to align with the rest of the data
Filling in a missing month with the mean of the month before and after

In [44]:
df_labor_force = df_labor_force.divide(1000)
df_labor_force.loc['2025-10-01'] = (df_labor_force.loc['2025-09-01'] + df_labor_force.loc['2025-11-01']).divide(2).round(3)

### Creating a Dictionary for use in transformations

In [45]:
dfs = {'us_labor_force':df_labor_force,
'us_construction':df_construction,
'us_education':df_education, 
'us_hospitality':df_hospitality, 
'us_manufacturing':df_manufacturing,}

In [46]:
#Checking Import
df_labor_force

,AKLF,ALLF,ARLF,AZLF,CALF,COLF,CTLF,DCLF,DELF,DSLF,...,SDLF,TNLF,TXLF,UTLF,VALF,VTLF,WALF,WILF,WVLF,WYLF
observation_date,,,,,,,,,,,,,,,,,,,,,
2015-01-01,362.704,2166.864,1331.412,3090.768,18818.212,2807.587,1912.878,379.620,458.015,NaN,...,449.519,3065.281,13005.030,1443.189,4237.002,353.493,3519.204,3093.599,795.082,302.001
2015-02-01,362.522,2169.495,1332.284,3093.823,18826.972,2808.391,1912.990,379.593,458.674,NaN,...,449.491,3067.489,12996.949,1446.330,4234.354,353.453,3523.168,3092.455,794.759,301.683
2015-03-01,362.346,2171.897,1333.305,3097.355,18838.028,2809.713,1912.140,379.763,459.436,NaN,...,449.521,3070.631,12994.457,1449.776,4232.923,353.266,3528.031,3091.803,794.694,301.424
2015-04-01,362.180,2173.967,1334.305,3101.717,18848.322,2811.615,1910.119,380.227,460.259,NaN,...,449.658,3074.122,12997.813,1453.518,4232.210,352.923,3533.695,3091.466,794.714,301.225
2015-05-01,361.928,2174.501,1334.929,3106.411,18852.828,2813.611,1907.097,380.770,461.075,NaN,...,449.843,3077.173,13004.689,1457.187,4231.145,352.438,3539.458,3091.078,794.426,301.027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-01,367.174,2385.522,1446.230,3814.082,19867.709,3254.009,1933.410,408.830,516.957,NaN,...,493.893,3543.930,15953.482,1843.780,4517.605,347.048,4059.900,3111.348,783.413,288.205
2025-11-01,367.709,2387.873,1448.832,3815.687,19878.800,3254.030,1933.758,408.918,517.116,NaN,...,494.081,3546.463,15962.121,1845.293,4518.582,346.688,4062.809,3115.444,783.871,288.447
2025-12-01,367.671,2387.810,1448.666,3814.917,19878.043,3254.073,1933.851,409.140,517.069,NaN,...,493.994,3545.878,15958.627,1845.208,4519.825,346.776,4062.730,3116.196,783.736,288.499
2026-01-01,368.676,2387.630,1451.314,3814.212,19861.662,3248.790,1931.253,407.975,516.219,NaN,...,493.467,3541.853,15955.231,1844.105,4518.567,345.430,4065.082,3121.154,782.645,288.454
2026-02-01,369.379,2386.304,1454.559,3800.676,19826.577,3238.456,1929.141,406.902,514.718,NaN,...,492.816,3532.590,15941.826,1840.984,4513.203,344.047,4066.446,3126.595,782.052,288.501

### Creating Mapping between State Abbrivations and Names
Every CSV uses the same 2 letter abbrivation to identify the State

In [47]:
mapping = {'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'DS': 'Unknown / Not a U.S. state',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WY': 'Wyoming'}

### Indivual Cleaning for Manufacturing / Construction
The columns for Manufacturing in District of Columbia and Alabama are given non-standard ID codes

The columns for Construction in Maryland, Nebraska, and Tennessee are given non-standard ID codes

In [48]:
manufacturing_mapping = {'SMS11000003000000001' : 'DC', 
                         'SMU01000003000000001SA' : 'AL'}
construction_mapping = {'SMS24000002000000001' : 'MD', 
                         'SMS31000002000000001' : 'NE',
                         'SMS47000002000000001': 'TN'}
for name, df in dfs.items():
    if name == 'us_manufacturing':
        df.rename(columns=manufacturing_mapping, inplace=True)
        df.drop(columns='SMU11000003000000001SA', inplace=True)
    elif name == 'us_construction':
        df.rename(columns=construction_mapping, inplace=True)
    else:
        pass

### Bulk Transformations
Changing each csv's different column code of (State + Survey) into the State Name

In [49]:
for name, df in dfs.items():
    df.rename(columns=lambda x: x[:2], inplace=True)
    df.rename(columns=mapping, inplace=True)
    df.rename_axis(None,inplace=True)

### Individual Cleaning
Labor Force has one null State and no information for October 2025

Construction has no information for Tennessee

In [50]:
# df_labor_force cleaning
df_labor_force.drop('Unknown / Not a U.S. state', axis=1, inplace=True)
#df_labor_force.drop('2025-10-01', axis=0, inplace=True)
#df_construction cleaning
df_construction.drop('Tennessee', axis=1, inplace=True)

### Transposing and Melting
Making it so that rows are states and columns are dates to align with Statistics Canada

In [51]:
dfs = {name: df.T for name, df in dfs.items()}
dfs = {name: df.melt(ignore_index=False) for name, df in dfs.items()}
dfs = {name: df.reset_index(names='State') for name, df in dfs.items()}
dfs = {name: df.rename(columns={'variable':"Date"}) for name, df in dfs.items()}

In [52]:
#Final Checking
for name, df in dfs.items():
    print(name)
    display(df)

us_labor_force

              State        Date      value
0            Alaska  2015-01-01    362.704
1           Alabama  2015-01-01   2166.864
2          Arkansas  2015-01-01   1331.412
3           Arizona  2015-01-01   3090.768
4        California  2015-01-01  18818.212
...             ...         ...        ...
6829        Vermont  2026-02-01    344.047
6830     Washington  2026-02-01   4066.446
6831      Wisconsin  2026-02-01   3126.595
6832  West Virginia  2026-02-01    782.052
6833        Wyoming  2026-02-01    288.501

[6834 rows x 3 columns]

us_construction

              State        Date  value
0            Alaska  2015-01-01   18.2
1           Alabama  2015-01-01   80.7
2          Arkansas  2015-01-01   47.7
3           Arizona  2015-01-01  124.2
4        California  2015-01-01  706.5
...             ...         ...    ...
6293        Vermont  2026-02-01   16.4
6294     Washington  2026-02-01  217.2
6295      Wisconsin  2026-02-01  153.7
6296  West Virginia  2026-02-01   36.7
6297        Wyoming  2026-02-01   23.9

[6298 rows x 3 columns]

us_education

              State        Date   value
0            Alaska  2015-01-01    47.8
1           Alabama  2015-01-01   231.3
2          Arkansas  2015-01-01   173.2
3           Arizona  2015-01-01   392.5
4        California  2015-01-01  2420.6
...             ...         ...     ...
6293       Virginia  2026-02-01   628.8
6294        Vermont  2026-02-01    65.9
6295     Washington  2026-02-01   570.1
6296      Wisconsin  2026-02-01   501.1
6297  West Virginia  2026-02-01   147.2

[6298 rows x 3 columns]

us_hospitality

              State        Date   value
0            Alaska  2015-01-01    34.9
1           Alabama  2015-01-01   186.9
2          Arkansas  2015-01-01   109.4
3           Arizona  2015-01-01   295.9
4        California  2015-01-01  1792.2
...             ...         ...     ...
6829        Vermont  2026-02-01    36.3
6830     Washington  2026-02-01   344.4
6831      Wisconsin  2026-02-01   289.8
6832  West Virginia  2026-02-01    70.7
6833        Wyoming  2026-02-01    38.5

[6834 rows x 3 columns]

us_manufacturing

               State        Date   value
0             Alaska  1990-01-01    12.4
1           Arkansas  1990-01-01   218.4
2            Arizona  1990-01-01   177.3
3         California  1990-01-01  1985.5
4           Colorado  1990-01-01   169.7
...              ...         ...     ...
22129        Vermont  2026-02-01    27.4
22130     Washington  2026-02-01   271.1
22131      Wisconsin  2026-02-01   451.5
22132  West Virginia  2026-02-01    44.9
22133        Wyoming  2026-02-01    10.3

[22134 rows x 3 columns]

### Saving to CSV

In [53]:
for name, df in dfs.items():
    df.to_csv(f'../data/clean/{name}.csv')