In [1]:
import pandas as pd
import plotly.express as px

In [3]:
url = '../data/clean/Cleaned Labour force by educational attainment.csv'
df = pd.read_csv(url, index_col=0)
df

,REF_DATE,GEO,Educational attainment,Age group,VALUE
0,2015-01,Canada,"Total, all education levels",15 to 24 years,53.2
1,2015-02,Canada,"Total, all education levels",15 to 24 years,53.6
2,2015-03,Canada,"Total, all education levels",15 to 24 years,54.1
3,2015-04,Canada,"Total, all education levels",15 to 24 years,53.5
4,2015-05,Canada,"Total, all education levels",15 to 24 years,59.2
...,...,...,...,...,...
53455,2025-11,British Columbia,Above bachelor's degree,65 years and over,19.6
53456,2025-12,British Columbia,Above bachelor's degree,65 years and over,18.2
53457,2026-01,British Columbia,Above bachelor's degree,65 years and over,19.0
53458,2026-02,British Columbia,Above bachelor's degree,65 years and over,24.1
53459,2026-03,British Columbia,Above bachelor's degree,65 years and over,25.1

In [5]:
df2 = df[(df['Age group'] == '25 to 54 years') 
   ]
df2

,REF_DATE,GEO,Educational attainment,Age group,VALUE
135,2015-01,Canada,"Total, all education levels",25 to 54 years,80.6
136,2015-02,Canada,"Total, all education levels",25 to 54 years,80.6
137,2015-03,Canada,"Total, all education levels",25 to 54 years,80.5
138,2015-04,Canada,"Total, all education levels",25 to 54 years,81.0
139,2015-05,Canada,"Total, all education levels",25 to 54 years,81.8
...,...,...,...,...,...
53185,2025-11,British Columbia,Above bachelor's degree,25 to 54 years,88.3
53186,2025-12,British Columbia,Above bachelor's degree,25 to 54 years,90.0
53187,2026-01,British Columbia,Above bachelor's degree,25 to 54 years,89.0
53188,2026-02,British Columbia,Above bachelor's degree,25 to 54 years,90.3
53189,2026-03,British Columbia,Above bachelor's degree,25 to 54 years,91.0

In [7]:
for edu in df2['Educational attainment'].value_counts().index:
    fig = px.line(df2[(df2['Educational attainment'] == edu)], 'REF_DATE', 'VALUE', color = 'GEO', title=f'{edu} Employment by Province')
    fig.show()

In [45]:
df3 = df[(df['Gender'] == 'Total - Gender')
   & ((df['Labour force characteristics'] == 'Full-time employment') | (df['Labour force characteristics'] == 'Part-time employment'))
   & (df['Age group'] == '15 years and over')
   & (df['Data type'] == 'Seasonally adjusted')
]
df3

,REF_DATE,GEO,Labour force characteristics,Gender,Age group,Statistics,Data type,VALUE
557820,2015-01-01,Canada,Full-time employment,Total - Gender,15 years and over,Estimate,Seasonally adjusted,14395.8
557821,2015-02-01,Canada,Full-time employment,Total - Gender,15 years and over,Estimate,Seasonally adjusted,14412.9
557822,2015-03-01,Canada,Full-time employment,Total - Gender,15 years and over,Estimate,Seasonally adjusted,14431.1
557823,2015-04-01,Canada,Full-time employment,Total - Gender,15 years and over,Estimate,Seasonally adjusted,14424.4
557824,2015-05-01,Canada,Full-time employment,Total - Gender,15 years and over,Estimate,Seasonally adjusted,14442.9
...,...,...,...,...,...,...,...,...
560785,2025-11-01,Canada,Part-time employment,Total - Gender,15 years and over,Estimate,Seasonally adjusted,3907.6
560786,2025-12-01,Canada,Part-time employment,Total - Gender,15 years and over,Estimate,Seasonally adjusted,3866.3
560787,2026-01-01,Canada,Part-time employment,Total - Gender,15 years and over,Estimate,Seasonally adjusted,3796.6
560788,2026-02-01,Canada,Part-time employment,Total - Gender,15 years and over,Estimate,Seasonally adjusted,3821.1
560789,2026-03-01,Canada,Part-time employment,Total - Gender,15 years and over,Estimate,Seasonally adjusted,3836.3

In [47]:
for province in df['GEO'].value_counts().index:
    fig = px.line(df3[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Labour force characteristics', title=f'{province} Employment by Part-Time vs. Full-Time')
    fig.show()

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\719573810.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df3[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Labour force characteristics', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\719573810.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df3[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Labour force characteristics', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\719573810.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df3[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Labour force characteristics', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\719573810.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df3[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Labour force characteristics', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\719573810.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df3[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Labour force characteristics', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\719573810.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df3[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Labour force characteristics', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\719573810.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df3[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Labour force characteristics', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\719573810.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df3[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Labour force characteristics', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\719573810.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df3[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Labour force characteristics', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\719573810.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df3[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Labour force characteristics', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\719573810.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df3[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Labour force characteristics', title=f'{province} Employment by Part-Time vs. Full-Time')

In [48]:
df4 = df[(df['Labour force characteristics'] == 'Participation rate') 
   & (df['Gender'] == 'Total - Gender')
   & (df['Data type'] == 'Seasonally adjusted')
   ]

In [50]:
for province in df['GEO'].value_counts().index:
    fig = px.line(df4[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Age group', title=f'{province} Employment by Part-Time vs. Full-Time')
    fig.show()

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\396811834.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df4[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Age group', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\396811834.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df4[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Age group', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\396811834.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df4[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Age group', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\396811834.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df4[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Age group', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\396811834.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df4[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Age group', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\396811834.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df4[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Age group', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\396811834.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df4[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Age group', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\396811834.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df4[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Age group', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\396811834.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df4[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Age group', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\396811834.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df4[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Age group', title=f'{province} Employment by Part-Time vs. Full-Time')

C:\Users\MGarn\AppData\Local\Temp\ipykernel_28956\396811834.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fig = px.line(df4[(df['GEO'] == province)], 'REF_DATE', 'VALUE', color = 'Age group', title=f'{province} Employment by Part-Time vs. Full-Time')

In [43]:
df['Labour force characteristics'].value_counts()

Labour force characteristics
Employment              65475
Population              63990
Labour force            63990
Unemployment            63990
Unemployment rate       63990
Participation rate      63990
Employment rate         63990
Full-time employment    59400
Part-time employment    59400
Name: count, dtype: int64

In [23]:
df['GEO'].value_counts().index

Index(['Canada', 'Newfoundland and Labrador', 'Prince Edward Island',
       'Nova Scotia', 'New Brunswick', 'Quebec', 'Ontario', 'Manitoba',
       'Saskatchewan', 'Alberta', 'British Columbia'],
      dtype='str', name='GEO')

In [30]:
df['Labour force characteristics'].value_counts().index

Index(['Employment', 'Population', 'Labour force', 'Unemployment',
       'Unemployment rate', 'Participation rate', 'Employment rate',
       'Full-time employment', 'Part-time employment'],
      dtype='str', name='Labour force characteristics')